import type { ImageSourcePropType } from "react-native";
import type { PlaceInfo } from "../types";
import { getImages } from "./get-image";

const imgList: ImageSourcePropType[] = getImages();

export const INITIAL_PLACE_INFO_LENGTH_ATOM = imgList.length;

export const INITIAL_PLACE_INFO_LIST_ATOM: PlaceInfo[] = [
  {
    index: 0,
    img: imgList[0],
    placeName: "三鷹の森ジブリ美術館",
    genre: "美術館",
    prefecture: "東京都",
    place: "井の頭公園",
    station: "吉祥寺駅",
    distance: "1.5km",
  },
  {
    index: 1,
    img: imgList[1],
    placeName: "三鷹の森ジブリ美術館",
    genre: "美術館",
    prefecture: "北海道",
    place: "井の頭公園",
    station: "吉祥寺駅",
    distance: "1.5km",
  },
  {
    index: 2,
    img: imgList[2],
    placeName: "三鷹の森ジブリ美術館",
    genre: "美術館",
    prefecture: "大阪府",
    place: "井の頭公園",
    station: "吉祥寺駅",
    distance: "1.5km",
  },
  {
    index: 3,
    img: imgList[3],
    placeName: "三鷹の森ジブリ美術館",
    genre: "美術館",
    prefecture: "沖縄県",
    place: "井の頭公園",
    station: "吉祥寺駅",
    distance: "1.5km",
  },
  {
    index: 4,
    img: imgList[4],
    placeName: "三鷹の森ジブリ美術館",
    genre: "美術館",
    prefecture: "京都府",
    place: "井の頭公園",
    station: "吉祥寺駅",
    distance: "1.5km",
  },
  {
    index: 5,
    img: imgList[5],
    placeName: "三鷹の森ジブリ美術館",
    genre: "美術館",
    prefecture: "愛知県",
    place: "井の頭公園",
    station: "吉祥寺駅",
    distance: "1.5km",
  },
  {
    index: 6,
    img: imgList[6],
    placeName: "三鷹の森ジブリ美術館",
    genre: "美術館",
    prefecture: "福岡県",
    place: "井の頭公園",
    station: "吉祥寺駅",
    distance: "1.5km",
  },
  {
    index: 7,
    img: imgList[7],
    placeName: "三鷹の森ジブリ美術館",
    genre: "美術館",
    prefecture: "神奈川県",
    place: "井の頭公園",
    station: "吉祥寺駅",
    distance: "1.5km",
  },
  {
    index: 8,
    img: imgList[8],
    placeName: "三鷹の森ジブリ美術館",
    genre: "美術館",
    prefecture: "埼玉県",
    place: "井の頭公園",
    station: "吉祥寺駅",
    distance: "1.5km",
  },
  {
    index: 9,
    img: imgList[9],
    placeName: "三鷹の森ジブリ美術館",
    genre: "美術館",
    prefecture: "千葉県",
    place: "井の頭公園",
    station: "吉祥寺駅",
    distance: "1.5km",
  },
];
